Senzing/senzing-environment

senzing-environment.py
=> issue-3 Starter function

README.md
=> issue-3 Add work-around for symlinks

docs/tutorial.md
=> issue-3 Improve documentation

docs/tutorial.md, senzing-environment.py
=> #10 Initial function

docs/tutorial.md
=> Issue 10.dockter.2

requirements.txt, senzing-environment.py, src/yum-packages.txt
=> Issue 14.dockter.2

senzing-environment.py
=> issue-14 Remove parse module

senzing-environment.py
=> #14 Use parsed_database_url

README.md, senzing-environment.py
=> Issue 22.macy.1

docs/tutorial.md, senzing-environment.py
=> update to new senzing-rest-api-specification url

CHANGELOG.md, senzing-environment.py
=> Issue 31.dockter.1

CHANGELOG.md, senzing-environment.py
=> Issue 33.dockter.1

senzing-environment.py
=> #36 UID of 0

senzing-environment.py
=> Expose API server on 8250

docs/reference.md, senzing-environment.py
=> #43 Example of update

docs/reference.md, senzing-environment.py
=> Issue 43.dockter.2

CHANGELOG.md
=> #43 Prepare for release

CHANGELOG.md, README.md, docs/reference.md, senzing-environment.py
=> Issue 48.dockter.1

CHANGELOG.md, README.md, senzing-environment.py
=> #48 Add 'init' to senzing-webapp-demo

CHANGELOG.md, README.md, senzing-environment.py
=> Issue 55.dockter.1

senzing-environment.py
=> Issue 56.dockter.1

CHANGELOG.md
=> #56 Prepare for version

senzing-environment.py
=> Issue 60.dockter.1

CHANGELOG.md, senzing-environment.py
=> Issue 60.dockter.2

senzing-environment.py
=> #60 Add senzing-webapp-demo

senzing-environment.py
=> #60 Add more info

senzing-environment.py
=> #60  Add comment

senzing-environment.py
=> #60 Syntax error

CHANGELOG.md, docs/reference.md, senzing-environment.py
=> #71  Added senzing-sshd.sh

senzing-environment.py
=> Issue 75.dockter.1

senzing-environment.py
=> #75 Savepoint

senzing-environment.py
=> #81 fix typo

senzing-environment.py
Issue number: #80 
New Senzing-Up uses new DOCKER_IMAGE_NAMES_* environment vars. Currently only using a couple of those added, including additional for future expansion. 
Comment out def file_docker_images_load() and def file_docker_images_save() for the time being. Michael initially added these for me to use. Built into senzing-up at this time due to complexity and changes to senzing-up.
New features for senzing-up to package and deploy sets of assets into non-net connected systems.
=> Issue 80.ant.2

senzing-environment.py
=> #85 Migrate from data 1.0.0 to 2.0.0

CHANGELOG.md, Dockerfile, senzing-environment.py
=> #97 Change from data 2.0.0 to 3.0.0

CONTRIBUTING.md, README.md, docs/reference.md, docs/tutorial.md, senzing-environment.py
=> #96 Migrate from master to main

.github/workflows/pylint.yaml, .pylintrc
=> #103 Add pylint

.github/CODEOWNERS, .github/workflows/add-dependabot-request-to-project-t-comm.yaml, .github/workflows/add-issue-to-project-t-comm.yaml, .github/workflows/add-triage-label.yaml, .github/workflows/build-docker-container.yaml, .github/workflows/identify-customer.yaml, .github/workflows/pylint.yaml
=> #116 Modify workflows

senzing-environment.py
=> #109 Remove ENTITY_TYPE

CHANGELOG.md, Dockerfile, senzing-environment.py
=> #122 Prepare for versioned release

.pylintrc, CHANGELOG.md, Dockerfile, senzing-environment.py
Update underlying docker images.
Issue number: #1
=> github-util: Update FROM version

.gitignore, README.md, docs/development.md, docs/errors.md, docs/examples.md, docs/tutorial.md
=> #129 Update links

README.md
=> #126 adding deprecation notes to README
